name: relate_anything
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.7.0
  - torchvision=0.8.0
  - torchaudio==0.7.0
  - cudatoolkit=10.1
  - pip
  - pip:
    - openmim
    - pre-commit
    - git+https://github.com/Jingkang50/OpenPSG